# Generated by Django 6.0 on 2025-12-31 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Gunung')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ketinggian (mdpl)')),
                ('location', models.CharField(max_length=200, verbose_name='Lokasi')),
                ('province', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Mudah'), ('medium', 'Menengah'), ('hard', 'Sulit'), ('extreme', 'Ekstrim')], default='medium', max_length=20, verbose_name='Tingkat Kesulitan')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mountains/', verbose_name='Gambar Utama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mountain',
                'verbose_name_plural': 'Mountains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Jalur')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(verbose_name='Deskripsi Jalur')),
                ('starting_point', models.CharField(max_length=200, verbose_name='Titik Awal')),
                ('duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durasi (Hari)')),
                ('duration_nights', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durasi (Malam)')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jarak (KM)')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Mudah'), ('medium', 'Menengah'), ('hard', 'Sulit'), ('extreme', 'Ekstrim')], default='medium', max_length=20, verbose_name='Tingkat Kesulitan')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga per Orang (Rp)')),
                ('max_participants', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maksimal Peserta')),
                ('facilities', models.TextField(help_text='Pisahkan dengan enter untuk setiap item', verbose_name='Fasilitas yang Disediakan')),
                ('requirements', models.TextField(help_text='Pisahkan dengan enter untuk setiap item', verbose_name='Persyaratan')),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='routes/gpx/', verbose_name='File GPX')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='mountains.mountain', verbose_name='Gunung')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['mountain', 'name'],
                'unique_together': {('mountain', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MountainGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Foto')),
                ('image', models.ImageField(upload_to='mountains/gallery/', verbose_name='Foto')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('photographer', models.CharField(blank=True, max_length=100, verbose_name='Fotografer')),
                ('taken_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Diambil')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Foto Unggulan')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='mountains.mountain', verbose_name='Gunung')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='mountains.route', verbose_name='Jalur (Opsional)')),
            ],
            options={
                'verbose_name': 'Mountain Gallery',
                'verbose_name_plural': 'Mountain Galleries',
                'ordering': ['mountain', 'order', '-created_at'],
            },
        ),
    ]
