# Generated by Django 5.2.3 on 2026-01-06 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_alter_booking_id_alter_bookingparticipant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_photo', models.ImageField(upload_to='checkins/id_cards/', verbose_name='Foto KTP/Identitas')),
                ('selfie_photo', models.ImageField(blank=True, null=True, upload_to='checkins/selfies/', verbose_name='Foto Selfie dengan KTP')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='checkins/qr_codes/', verbose_name='QR Code')),
                ('qr_data', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Data QR Code')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Verifikasi')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Alasan Penolakan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='bookings.booking', verbose_name='Booking')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='bookings.bookingparticipant', verbose_name='Peserta')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_checkins', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi Oleh')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'participant')},
            },
        ),
    ]
