# Generated by Django 5.2.3 on 2026-01-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_alter_checkin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
