# Generated by Django 6.0 on 2026-01-02 23:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mountains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai Pendakian')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai Pendakian')),
                ('num_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jumlah Peserta')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga per Orang')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Harga')),
                ('payment_method', models.CharField(blank=True, choices=[('transfer', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('credit_card', 'Kartu Kredit')], max_length=50, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='bookings/payments/', verbose_name='Bukti Pembayaran')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Catatan Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='mountains.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('id_number', models.CharField(max_length=50, verbose_name='NIK/No. Identitas')),
                ('date_of_birth', models.DateField(verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(choices=[('male', 'Laki-laki'), ('female', 'Perempuan')], max_length=10, verbose_name='Jenis Kelamin')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5, verbose_name='Golongan Darah')),
                ('emergency_contact_name', models.CharField(max_length=200, verbose_name='Nama Kontak Darurat')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Telepon Kontak Darurat')),
                ('emergency_contact_relation', models.CharField(help_text='Contoh: Orang Tua, Saudara, Pasangan', max_length=50, verbose_name='Hubungan')),
                ('health_notes', models.TextField(blank=True, help_text='Riwayat penyakit, alergi, dll', verbose_name='Catatan Kesehatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Participant',
                'verbose_name_plural': 'Booking Participants',
                'ordering': ['booking', 'full_name'],
            },
        ),
    ]
