# Generated by Django 5.2.3 on 2026-01-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_id_alter_bookingparticipant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingparticipant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Peserta Booking', 'verbose_name_plural': 'Peserta Booking'},
        ),
        migrations.AddField(
            model_name='bookingparticipant',
            name='address',
            field=models.TextField(blank=True, verbose_name='Alamat Lengkap'),
        ),
        migrations.AddField(
            model_name='bookingparticipant',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kota/Kabupaten'),
        ),
        migrations.AddField(
            model_name='bookingparticipant',
            name='health_certificate',
            field=models.FileField(blank=True, null=True, upload_to='participants/health_certificates/', verbose_name='Surat Keterangan Sehat'),
        ),
        migrations.AddField(
            model_name='bookingparticipant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kode Pos'),
        ),
        migrations.AddField(
            model_name='bookingparticipant',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='bookingparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookingparticipant',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3, verbose_name='Golongan Darah'),
        ),
        migrations.AlterField(
            model_name='bookingparticipant',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bookings.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='bookingparticipant',
            name='emergency_contact_relation',
            field=models.CharField(max_length=50, verbose_name='Hubungan'),
        ),
        migrations.AlterField(
            model_name='bookingparticipant',
            name='health_notes',
            field=models.TextField(blank=True, verbose_name='Catatan Kesehatan'),
        ),
        migrations.AlterField(
            model_name='bookingparticipant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
